apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  miapp1
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: app-desarollo
    server: 'https://kubernetes.default.svc'
  source:
    path: DEV-DESAROLLO/k8s/helm-repo
    repoURL: 'https://github.com/CODEXEDYX/DEV-DESAROLLO.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true