 apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webapp-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: webapp
spec:
  replicas: {{ .Values.backend_replicase }}
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: {{ .Values.backend_images }}
        ports:
        - containerPort: {{ .Values.backend_port }}
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongo-secret
              key: mongo-username
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongo-secret
              key: mongo-password 
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-mongodb-configmap
              key: database_url