apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: mongo
spec:
  replicas: {{ .Values.mongo_replicase }}
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.mongo_images }}
        ports:
        - containerPort: {{ .Values.mongo_port }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongo-secret
              key: mongo-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongo-secret
              key: mongo-password  
              