apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.webhook.jenkins: |
    url: http://192.168.59.120:30000/job/my_backend/build?token=11c016ab9402e40756a4c3535008cfb095
    basicAuth:
      secretName: webhookk
  template.jenkins-trigger: |
    webhook:
      jenkins:
        method: POST
        path: /job/desarollo/build

