apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: {{ .Values.backend_port }}
      targetPort: {{ .Values.backend_port }}
      nodePort: 30100