apiVersion: v1
kind: Service
metadata:
  name: webapp-frontend-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: app-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend_port }}
      targetPort: {{ .Values.frontend_port }}
      nodePort: 30200

