apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: {{ .Values.mongo_port }}
      targetPort: {{ .Values.mongo_port }}
