apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: mongo-express
  ports:
    - protocol:  TCP
      port: {{ .Values.mexpress_port }}
      targetPort: {{ .Values.mexpress_port }}
      nodePort: 30000
